@extends('layouts.admin')

@push('styles')
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endpush

@section('title', 'Bon In')
@section('page_title', 'Create Standalone Bon In')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Create Standalone Bon In (Type 3 Only)</h3>
                    <div class="card-tools">
                        <a href="{{ route('receivables.index') }}" class="btn btn-sm btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back
                        </a>
                    </div>
                </div>

                <form action="{{ route('receivables.store_standalone') }}" method="POST" id="bonInForm">
                    @csrf

                    <div class="card-body">
                        @if (session('error'))
                            <div class="alert alert-danger">{{ session('error') }}</div>
                        @endif

                        <div class="alert alert-info">
                            <i class="fas fa-info-circle"></i> Bon In Number will be auto-generated by type:
                            Type 3 → 300001, 300002…
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="bon_in_type">Bon In Type <span class="text-danger">*</span></label>
                                    <input type="hidden" name="bon_in_type" value="3">
                                    <input type="text" class="form-control" value="3 - Adjustment In" readonly>
                                    @error('bon_in_type')
                                        <span class="invalid-feedback">{{ $message }}</span>
                                    @enderror
                                    <small class="form-text text-muted">
                                        Standalone Bon In is only for stock Adjustment In.
                                    </small>
                                </div>
                            </div>

                            <div class="col-md-6">

                                <div class="form-group">
                                    <label for="notes">Adjustment Reason <span class="text-danger">*</span></label>
                                    <textarea name="notes" id="notes" rows="5" class="form-control @error('notes') is-invalid @enderror">{{ old('notes') }}</textarea>
                                    @error('notes')
                                        <span class="invalid-feedback">{{ $message }}</span>
                                    @enderror
                                    <small class="form-text text-muted">
                                        Explain why this stock adjustment is needed.
                                    </small>
                                </div>
                            </div>
                        </div>

                        <hr>
                        <h6>Items to Receive <span class="text-danger">*</span></h6>
                        <table class="table table-bordered" id="itemsTable">
                            <thead>
                                <tr>
                                    <th width="40%">Item</th>
                                    <th width="20%">UOM</th>
                                    <th width="20%">Quantity Received</th>
                                    <th width="10%">Action</th>
                                </tr>
                            </thead>
                            <tbody id="itemsBody">
                                <tr class="item-row">
                                    <td>
                                        <select name="items[0][item_id]" class="form-control item-select select2-item"
                                            required style="width: 100%;">
                                            <option value="">Select Item</option>
                                            @foreach ($items as $item)
                                                <option value="{{ $item->id }}" data-item="{{ json_encode($item) }}">
                                                    {{ $item->code }} - {{ $item->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <select name="items[0][uom_id]" class="form-control uom-select" required disabled>
                                            <option value="">Select UOM</option>
                                        </select>
                                    </td>
                                    <td>
                                        <input type="number" name="items[0][quantity_received]" class="form-control"
                                            step="0.01" min="0.01" required>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-danger remove-item" disabled>
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-sm btn-success" id="addItemRow">
                            <i class="fas fa-plus"></i> Add Item
                        </button>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-save"></i> Create Bon In
                        </button>
                        <a href="{{ route('receivables.index') }}" class="btn btn-secondary">
                            <i class="fas fa-times"></i> Cancel
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        let rowIndex = 0;
        const items = @json($items);

        $(document).ready(function() {
            // Handle item selection to populate UOMs
            $(document).on('change', '.item-select', function() {
                const itemId = $(this).val();
                const uomSelect = $(this).closest('tr').find('.uom-select');

                uomSelect.html('<option value="">Select UOM</option>');
                uomSelect.prop('disabled', true);

                if (itemId) {
                    const item = items.find(i => i.id == itemId);
                    if (item && item.item_uoms) {
                        item.item_uoms.forEach(itemUom => {
                            uomSelect.append(
                                `<option value="${itemUom.uom.id}">${itemUom.uom.name} (${itemUom.uom.code})</option>`
                            );
                        });
                        uomSelect.prop('disabled', false);
                    }
                }
            });

            // Add new item row
            $('#addItemRow').click(function() {
                rowIndex++;
                const newRow = `
                    <tr class="item-row">
                        <td>
                            <select name="items[${rowIndex}][item_id]" class="form-control item-select select2-item" required style="width: 100%;">
                                <option value="">Select Item</option>
                                @foreach ($items as $item)
                                    <option value="{{ $item->id }}">{{ $item->code }} - {{ $item->name }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                            <select name="items[${rowIndex}][uom_id]" class="form-control uom-select" required disabled>
                                <option value="">Select UOM</option>
                            </select>
                        </td>
                        <td>
                            <input type="number" name="items[${rowIndex}][quantity_received]"
                                class="form-control" step="0.01" min="0.01" required>
                        </td>
                        <td>
                            <button type="button" class="btn btn-sm btn-danger remove-item">
                                <i class="fas fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                `;
                $('#itemsBody').append(newRow);
                updateRemoveButtons();
                initItemSelect2();
            });

            // Remove item row
            $(document).on('click', '.remove-item', function() {
                $(this).closest('tr').remove();
                updateRemoveButtons();
            });

            // Update remove buttons (disable if only 1 row)
            function updateRemoveButtons() {
                const rowCount = $('.item-row').length;
                $('.remove-item').prop('disabled', rowCount === 1);
            }

            // Initialize select2 for item dropdowns
            function initItemSelect2() {
                $('.select2-item').each(function() {
                    if (!$(this).hasClass('select2-hidden-accessible')) {
                        $(this).select2({
                            theme: 'bootstrap4',
                            placeholder: 'Select Item',
                            allowClear: true,
                            width: '100%'
                        });
                    }
                });
            }

            // Initialize on page load
            initItemSelect2();
        });
    </script>
@endsection
